### ISSUE TITLE
Add R Development Guide

### ISSUE THREAD

**Issue by SaranjeetKaur** [rstudio/bookdown.org#165]
How to add the [R Development Guide](https://contributor.r-project.org/rdevguide/) to this list?

CC: @hturner

**Comment by SaranjeetKaur** [comment]
Update: We have added a cover image and the url to the YAML metadata on the rdevguide repo

CC: @cderv

**Comment by cderv** [comment]
Cover does not seem loaded yet on the website, is it ? https://contributor.r-project.org/rdevguide/ Or is it the R Logo ? 

When did you do the update also ? 

Website is updated every thursday.

**Comment by cderv** [comment]
It has been part of the today's update 
https://github.com/rstudio/bookdown.org/commit/c241b719712b47ca38c7ca156a854669868b5c3d#diff-164d00e20368f6ce12f30106869845d32a01121bb5ca3aacbc3f8e921dbff00d

**Comment by SaranjeetKaur** [comment]
> Cover does not seem loaded yet on the website, is it ? https://contributor.r-project.org/rdevguide/ Or is it the R Logo ?
> 
> When did you do the update also ?
> 
> Website is updated every thursday.

Yes it is the R Logo

**Comment by SaranjeetKaur** [comment]
Thanks for the update on the website!
