### ISSUE TITLE
Build error : Failed to retrieve package sources for MASS 7.3-60.0.1 from CRAN

### ISSUE THREAD

**Issue by LXHe** [rstudio/bookdown.org#289]
Hi, thanks for creating such an amazing bookdown tool. I have been using it these days and have republished a manuscript multiple times with no error. But 2 days ago, I came across an error while republishing my latest writing:

`Installing MASS (7.3-60.0.1) ... 
curl: HTTP 200 https://cran.rstudio.com/src/contrib/PACKAGES.rds
curl: HTTP 404 https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-60.0.1.tar.gz
curl: (22) The requested URL returned error: 404 
curl: HTTP 404 https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-60.0.1.tar.gz
curl: (22) The requested URL returned error: 404 
curl: HTTP 404 https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-60.0.1.tar.gz
curl: (22) The requested URL returned error: 404 
curl: HTTP 404 https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-60.0.1.tar.gz
curl: (22) The requested URL returned error: 404 
curl: HTTP 404 https://cran.rstudio.com/src/contrib/Archive/MASS/MASS_7.3-60.0.1.tar.gz
curl: (22) The requested URL returned error: 404 
FAILED
Error in getSourceForPkgRecord(pkgRecord, srcDir(project), availablePackagesSource(repos = repos), : Failed to retrieve package sources for MASS 7.3-60.0.1 from CRAN (internet connectivity issue?)

Unable to fully restore the R packages associated with this deployment.
Please review the preceding messages to determine which package
encountered installation difficulty and the cause of the failure.`

My R version is 4.3.3 and I have installed the latest MASS package locally but still get the error. I saw a similar issue [here]( https://github.com/rstudio/bookdown.org/issues/98). Don't know if it is also a hosting service issue. Can you help me out? Thank you.

**Comment by cderv** [comment]
It seems this package is not available somehow in cran.rstudio.com

You could try a previous MASS version, or wait for this package to be synced. We can't do much about that from our end unfortunately.

**Comment by LXHe** [comment]
Thanks! I tried a previous MASS version and that worked! 
It seems that rmarkdown::publish_site() also works.
